// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application_metadata_message.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplicationMetadataMessage_Type int32

const (
	ApplicationMetadataMessage_UNKNOWN                                  ApplicationMetadataMessage_Type = 0
	ApplicationMetadataMessage_CHAT_MESSAGE                             ApplicationMetadataMessage_Type = 1
	ApplicationMetadataMessage_CONTACT_UPDATE                           ApplicationMetadataMessage_Type = 2
	ApplicationMetadataMessage_MEMBERSHIP_UPDATE_MESSAGE                ApplicationMetadataMessage_Type = 3
	ApplicationMetadataMessage_PAIR_INSTALLATION                        ApplicationMetadataMessage_Type = 4
	ApplicationMetadataMessage_SYNC_INSTALLATION                        ApplicationMetadataMessage_Type = 5
	ApplicationMetadataMessage_REQUEST_ADDRESS_FOR_TRANSACTION          ApplicationMetadataMessage_Type = 6
	ApplicationMetadataMessage_ACCEPT_REQUEST_ADDRESS_FOR_TRANSACTION   ApplicationMetadataMessage_Type = 7
	ApplicationMetadataMessage_DECLINE_REQUEST_ADDRESS_FOR_TRANSACTION  ApplicationMetadataMessage_Type = 8
	ApplicationMetadataMessage_REQUEST_TRANSACTION                      ApplicationMetadataMessage_Type = 9
	ApplicationMetadataMessage_SEND_TRANSACTION                         ApplicationMetadataMessage_Type = 10
	ApplicationMetadataMessage_DECLINE_REQUEST_TRANSACTION              ApplicationMetadataMessage_Type = 11
	ApplicationMetadataMessage_SYNC_INSTALLATION_CONTACT                ApplicationMetadataMessage_Type = 12
	ApplicationMetadataMessage_SYNC_INSTALLATION_ACCOUNT                ApplicationMetadataMessage_Type = 13
	ApplicationMetadataMessage_SYNC_INSTALLATION_PUBLIC_CHAT            ApplicationMetadataMessage_Type = 14
	ApplicationMetadataMessage_CONTACT_CODE_ADVERTISEMENT               ApplicationMetadataMessage_Type = 15
	ApplicationMetadataMessage_PUSH_NOTIFICATION_REGISTRATION           ApplicationMetadataMessage_Type = 16
	ApplicationMetadataMessage_PUSH_NOTIFICATION_REGISTRATION_RESPONSE  ApplicationMetadataMessage_Type = 17
	ApplicationMetadataMessage_PUSH_NOTIFICATION_QUERY                  ApplicationMetadataMessage_Type = 18
	ApplicationMetadataMessage_PUSH_NOTIFICATION_QUERY_RESPONSE         ApplicationMetadataMessage_Type = 19
	ApplicationMetadataMessage_PUSH_NOTIFICATION_REQUEST                ApplicationMetadataMessage_Type = 20
	ApplicationMetadataMessage_PUSH_NOTIFICATION_RESPONSE               ApplicationMetadataMessage_Type = 21
	ApplicationMetadataMessage_EMOJI_REACTION                           ApplicationMetadataMessage_Type = 22
	ApplicationMetadataMessage_GROUP_CHAT_INVITATION                    ApplicationMetadataMessage_Type = 23
	ApplicationMetadataMessage_CHAT_IDENTITY                            ApplicationMetadataMessage_Type = 24
	ApplicationMetadataMessage_COMMUNITY_DESCRIPTION                    ApplicationMetadataMessage_Type = 25
	ApplicationMetadataMessage_COMMUNITY_INVITATION                     ApplicationMetadataMessage_Type = 26
	ApplicationMetadataMessage_COMMUNITY_REQUEST_TO_JOIN                ApplicationMetadataMessage_Type = 27
	ApplicationMetadataMessage_PIN_MESSAGE                              ApplicationMetadataMessage_Type = 28
	ApplicationMetadataMessage_EDIT_MESSAGE                             ApplicationMetadataMessage_Type = 29
	ApplicationMetadataMessage_STATUS_UPDATE                            ApplicationMetadataMessage_Type = 30
	ApplicationMetadataMessage_DELETE_MESSAGE                           ApplicationMetadataMessage_Type = 31
	ApplicationMetadataMessage_SYNC_INSTALLATION_COMMUNITY              ApplicationMetadataMessage_Type = 32
	ApplicationMetadataMessage_ANONYMOUS_METRIC_BATCH                   ApplicationMetadataMessage_Type = 33
	ApplicationMetadataMessage_SYNC_CHAT_REMOVED                        ApplicationMetadataMessage_Type = 34
	ApplicationMetadataMessage_SYNC_CHAT_MESSAGES_READ                  ApplicationMetadataMessage_Type = 35
	ApplicationMetadataMessage_BACKUP                                   ApplicationMetadataMessage_Type = 36
	ApplicationMetadataMessage_SYNC_SETTING_CURRENCY                    ApplicationMetadataMessage_Type = 37
	ApplicationMetadataMessage_SYNC_SETTING_GIF_RECENTS                 ApplicationMetadataMessage_Type = 38
	ApplicationMetadataMessage_SYNC_SETTING_GIF_FAVOURITES              ApplicationMetadataMessage_Type = 39
	ApplicationMetadataMessage_SYNC_SETTING_MESSAGES_FROM_CONTACTS_ONLY ApplicationMetadataMessage_Type = 40
	ApplicationMetadataMessage_SYNC_SETTING_PREFERRED_NAME              ApplicationMetadataMessage_Type = 41
	ApplicationMetadataMessage_SYNC_SETTING_PREVIEW_PRIVACY             ApplicationMetadataMessage_Type = 42
	ApplicationMetadataMessage_SYNC_SETTING_PROFILE_PICTURES_SHOW_TO    ApplicationMetadataMessage_Type = 43
	ApplicationMetadataMessage_SYNC_SETTING_PROFILE_PICTURES_VISIBILITY ApplicationMetadataMessage_Type = 44
	ApplicationMetadataMessage_SYNC_SETTING_SEND_STATUS_UPDATES         ApplicationMetadataMessage_Type = 45
	ApplicationMetadataMessage_SYNC_SETTING_STICKERS_PACKS_INSTALLED    ApplicationMetadataMessage_Type = 46
	ApplicationMetadataMessage_SYNC_SETTING_STICKERS_PACKS_PENDING      ApplicationMetadataMessage_Type = 47
	ApplicationMetadataMessage_SYNC_SETTING_STICKERS_RECENT_STICKERS    ApplicationMetadataMessage_Type = 48
	ApplicationMetadataMessage_SYNC_SETTING_TELEMETRY_SERVER_URL        ApplicationMetadataMessage_Type = 49
)

var ApplicationMetadataMessage_Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "CHAT_MESSAGE",
	2:  "CONTACT_UPDATE",
	3:  "MEMBERSHIP_UPDATE_MESSAGE",
	4:  "PAIR_INSTALLATION",
	5:  "SYNC_INSTALLATION",
	6:  "REQUEST_ADDRESS_FOR_TRANSACTION",
	7:  "ACCEPT_REQUEST_ADDRESS_FOR_TRANSACTION",
	8:  "DECLINE_REQUEST_ADDRESS_FOR_TRANSACTION",
	9:  "REQUEST_TRANSACTION",
	10: "SEND_TRANSACTION",
	11: "DECLINE_REQUEST_TRANSACTION",
	12: "SYNC_INSTALLATION_CONTACT",
	13: "SYNC_INSTALLATION_ACCOUNT",
	14: "SYNC_INSTALLATION_PUBLIC_CHAT",
	15: "CONTACT_CODE_ADVERTISEMENT",
	16: "PUSH_NOTIFICATION_REGISTRATION",
	17: "PUSH_NOTIFICATION_REGISTRATION_RESPONSE",
	18: "PUSH_NOTIFICATION_QUERY",
	19: "PUSH_NOTIFICATION_QUERY_RESPONSE",
	20: "PUSH_NOTIFICATION_REQUEST",
	21: "PUSH_NOTIFICATION_RESPONSE",
	22: "EMOJI_REACTION",
	23: "GROUP_CHAT_INVITATION",
	24: "CHAT_IDENTITY",
	25: "COMMUNITY_DESCRIPTION",
	26: "COMMUNITY_INVITATION",
	27: "COMMUNITY_REQUEST_TO_JOIN",
	28: "PIN_MESSAGE",
	29: "EDIT_MESSAGE",
	30: "STATUS_UPDATE",
	31: "DELETE_MESSAGE",
	32: "SYNC_INSTALLATION_COMMUNITY",
	33: "ANONYMOUS_METRIC_BATCH",
	34: "SYNC_CHAT_REMOVED",
	35: "SYNC_CHAT_MESSAGES_READ",
	36: "BACKUP",
	37: "SYNC_SETTING_CURRENCY",
	38: "SYNC_SETTING_GIF_RECENTS",
	39: "SYNC_SETTING_GIF_FAVOURITES",
	40: "SYNC_SETTING_MESSAGES_FROM_CONTACTS_ONLY",
	41: "SYNC_SETTING_PREFERRED_NAME",
	42: "SYNC_SETTING_PREVIEW_PRIVACY",
	43: "SYNC_SETTING_PROFILE_PICTURES_SHOW_TO",
	44: "SYNC_SETTING_PROFILE_PICTURES_VISIBILITY",
	45: "SYNC_SETTING_SEND_STATUS_UPDATES",
	46: "SYNC_SETTING_STICKERS_PACKS_INSTALLED",
	47: "SYNC_SETTING_STICKERS_PACKS_PENDING",
	48: "SYNC_SETTING_STICKERS_RECENT_STICKERS",
	49: "SYNC_SETTING_TELEMETRY_SERVER_URL",
}

var ApplicationMetadataMessage_Type_value = map[string]int32{
	"UNKNOWN":                                  0,
	"CHAT_MESSAGE":                             1,
	"CONTACT_UPDATE":                           2,
	"MEMBERSHIP_UPDATE_MESSAGE":                3,
	"PAIR_INSTALLATION":                        4,
	"SYNC_INSTALLATION":                        5,
	"REQUEST_ADDRESS_FOR_TRANSACTION":          6,
	"ACCEPT_REQUEST_ADDRESS_FOR_TRANSACTION":   7,
	"DECLINE_REQUEST_ADDRESS_FOR_TRANSACTION":  8,
	"REQUEST_TRANSACTION":                      9,
	"SEND_TRANSACTION":                         10,
	"DECLINE_REQUEST_TRANSACTION":              11,
	"SYNC_INSTALLATION_CONTACT":                12,
	"SYNC_INSTALLATION_ACCOUNT":                13,
	"SYNC_INSTALLATION_PUBLIC_CHAT":            14,
	"CONTACT_CODE_ADVERTISEMENT":               15,
	"PUSH_NOTIFICATION_REGISTRATION":           16,
	"PUSH_NOTIFICATION_REGISTRATION_RESPONSE":  17,
	"PUSH_NOTIFICATION_QUERY":                  18,
	"PUSH_NOTIFICATION_QUERY_RESPONSE":         19,
	"PUSH_NOTIFICATION_REQUEST":                20,
	"PUSH_NOTIFICATION_RESPONSE":               21,
	"EMOJI_REACTION":                           22,
	"GROUP_CHAT_INVITATION":                    23,
	"CHAT_IDENTITY":                            24,
	"COMMUNITY_DESCRIPTION":                    25,
	"COMMUNITY_INVITATION":                     26,
	"COMMUNITY_REQUEST_TO_JOIN":                27,
	"PIN_MESSAGE":                              28,
	"EDIT_MESSAGE":                             29,
	"STATUS_UPDATE":                            30,
	"DELETE_MESSAGE":                           31,
	"SYNC_INSTALLATION_COMMUNITY":              32,
	"ANONYMOUS_METRIC_BATCH":                   33,
	"SYNC_CHAT_REMOVED":                        34,
	"SYNC_CHAT_MESSAGES_READ":                  35,
	"BACKUP":                                   36,
	"SYNC_SETTING_CURRENCY":                    37,
	"SYNC_SETTING_GIF_RECENTS":                 38,
	"SYNC_SETTING_GIF_FAVOURITES":              39,
	"SYNC_SETTING_MESSAGES_FROM_CONTACTS_ONLY": 40,
	"SYNC_SETTING_PREFERRED_NAME":              41,
	"SYNC_SETTING_PREVIEW_PRIVACY":             42,
	"SYNC_SETTING_PROFILE_PICTURES_SHOW_TO":    43,
	"SYNC_SETTING_PROFILE_PICTURES_VISIBILITY": 44,
	"SYNC_SETTING_SEND_STATUS_UPDATES":         45,
	"SYNC_SETTING_STICKERS_PACKS_INSTALLED":    46,
	"SYNC_SETTING_STICKERS_PACKS_PENDING":      47,
	"SYNC_SETTING_STICKERS_RECENT_STICKERS":    48,
	"SYNC_SETTING_TELEMETRY_SERVER_URL":        49,
}

func (x ApplicationMetadataMessage_Type) String() string {
	return proto.EnumName(ApplicationMetadataMessage_Type_name, int32(x))
}

func (ApplicationMetadataMessage_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad09a6406fcf24c7, []int{0, 0}
}

type ApplicationMetadataMessage struct {
	// Signature of the payload field
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// This is the encoded protobuf of the application level message, i.e ChatMessage
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// The type of protobuf message sent
	Type                 ApplicationMetadataMessage_Type `protobuf:"varint,3,opt,name=type,proto3,enum=protobuf.ApplicationMetadataMessage_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ApplicationMetadataMessage) Reset()         { *m = ApplicationMetadataMessage{} }
func (m *ApplicationMetadataMessage) String() string { return proto.CompactTextString(m) }
func (*ApplicationMetadataMessage) ProtoMessage()    {}
func (*ApplicationMetadataMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad09a6406fcf24c7, []int{0}
}

func (m *ApplicationMetadataMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationMetadataMessage.Unmarshal(m, b)
}
func (m *ApplicationMetadataMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationMetadataMessage.Marshal(b, m, deterministic)
}
func (m *ApplicationMetadataMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationMetadataMessage.Merge(m, src)
}
func (m *ApplicationMetadataMessage) XXX_Size() int {
	return xxx_messageInfo_ApplicationMetadataMessage.Size(m)
}
func (m *ApplicationMetadataMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationMetadataMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationMetadataMessage proto.InternalMessageInfo

func (m *ApplicationMetadataMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ApplicationMetadataMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ApplicationMetadataMessage) GetType() ApplicationMetadataMessage_Type {
	if m != nil {
		return m.Type
	}
	return ApplicationMetadataMessage_UNKNOWN
}

func init() {
	proto.RegisterEnum("protobuf.ApplicationMetadataMessage_Type", ApplicationMetadataMessage_Type_name, ApplicationMetadataMessage_Type_value)
	proto.RegisterType((*ApplicationMetadataMessage)(nil), "protobuf.ApplicationMetadataMessage")
}

func init() {
	proto.RegisterFile("application_metadata_message.proto", fileDescriptor_ad09a6406fcf24c7)
}

var fileDescriptor_ad09a6406fcf24c7 = []byte{
	// 834 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x95, 0x4b, 0x53, 0x1b, 0x39,
	0x10, 0xc7, 0x97, 0x84, 0x85, 0xa4, 0x0d, 0x44, 0x74, 0x20, 0x98, 0xb7, 0x31, 0x21, 0x40, 0x92,
	0x75, 0xf6, 0x71, 0xdc, 0xda, 0x83, 0xac, 0x69, 0xdb, 0x0a, 0x33, 0xd2, 0x44, 0xd2, 0x98, 0xf2,
	0x5e, 0x54, 0xce, 0xc6, 0x9b, 0xa2, 0x2a, 0x09, 0xae, 0xe0, 0x1c, 0xf8, 0x0c, 0xfb, 0x79, 0xf7,
	0x9e, 0xd2, 0xf8, 0x8d, 0x21, 0x9c, 0x6c, 0x75, 0xff, 0xd4, 0xad, 0xfe, 0x77, 0xb7, 0x0d, 0xe5,
	0x76, 0xb7, 0xfb, 0xe9, 0xe2, 0x9f, 0x76, 0xef, 0xe2, 0xf2, 0x8b, 0xff, 0xdc, 0xe9, 0xb5, 0x3f,
	0xb4, 0x7b, 0x6d, 0xff, 0xb9, 0x73, 0x75, 0xd5, 0xfe, 0xd8, 0xa9, 0x74, 0xbf, 0x5e, 0xf6, 0x2e,
	0xf1, 0x51, 0xfe, 0xf1, 0xfe, 0xdb, 0xbf, 0xe5, 0xff, 0x96, 0x61, 0x8b, 0x8f, 0x2f, 0x24, 0x03,
	0x3e, 0xe9, 0xe3, 0xb8, 0x03, 0x8f, 0xaf, 0x2e, 0x3e, 0x7e, 0x69, 0xf7, 0xbe, 0x7d, 0xed, 0x14,
	0xe7, 0x4a, 0x73, 0x27, 0x4b, 0x66, 0x6c, 0xc0, 0x22, 0x2c, 0x76, 0xdb, 0xd7, 0x9f, 0x2e, 0xdb,
	0x1f, 0x8a, 0x0f, 0x72, 0xdf, 0xf0, 0x88, 0x7f, 0xc1, 0x7c, 0xef, 0xba, 0xdb, 0x29, 0x3e, 0x2c,
	0xcd, 0x9d, 0xac, 0xfc, 0x7e, 0x5a, 0x19, 0xe6, 0xab, 0xdc, 0x9d, 0xab, 0xe2, 0xae, 0xbb, 0x1d,
	0x93, 0x5f, 0x2b, 0xff, 0x5f, 0x80, 0xf9, 0x70, 0xc4, 0x02, 0x2c, 0x66, 0xea, 0x4c, 0xe9, 0x73,
	0xc5, 0x7e, 0x42, 0x06, 0x4b, 0xa2, 0xc1, 0x9d, 0x4f, 0xc8, 0x5a, 0x5e, 0x27, 0x36, 0x87, 0x08,
	0x2b, 0x42, 0x2b, 0xc7, 0x85, 0xf3, 0x59, 0x1a, 0x71, 0x47, 0xec, 0x01, 0xee, 0xc2, 0x66, 0x42,
	0x49, 0x95, 0x8c, 0x6d, 0xc8, 0x74, 0x60, 0x1e, 0x5d, 0x79, 0x88, 0xeb, 0xb0, 0x9a, 0x72, 0x69,
	0xbc, 0x54, 0xd6, 0xf1, 0x38, 0xe6, 0x4e, 0x6a, 0xc5, 0xe6, 0x83, 0xd9, 0xb6, 0x94, 0x98, 0x36,
	0xff, 0x8c, 0x87, 0xb0, 0x6f, 0xe8, 0x5d, 0x46, 0xd6, 0x79, 0x1e, 0x45, 0x86, 0xac, 0xf5, 0x35,
	0x6d, 0xbc, 0x33, 0x5c, 0x59, 0x2e, 0x72, 0x68, 0x01, 0x5f, 0xc2, 0x0b, 0x2e, 0x04, 0xa5, 0xce,
	0xdf, 0xc7, 0x2e, 0xe2, 0x2b, 0x38, 0x8e, 0x48, 0xc4, 0x52, 0xd1, 0xbd, 0xf0, 0x23, 0xdc, 0x80,
	0xa7, 0x43, 0x68, 0xd2, 0xf1, 0x18, 0xd7, 0x80, 0x59, 0x52, 0xd1, 0x94, 0x15, 0x70, 0x1f, 0xb6,
	0x6f, 0xc6, 0x9e, 0x04, 0x0a, 0x41, 0x9a, 0x99, 0x22, 0xfd, 0x40, 0x40, 0xb6, 0x74, 0xbb, 0x9b,
	0x0b, 0xa1, 0x33, 0xe5, 0xd8, 0x32, 0x1e, 0xc0, 0xee, 0xac, 0x3b, 0xcd, 0xaa, 0xb1, 0x14, 0x3e,
	0xf4, 0x85, 0xad, 0xe0, 0x1e, 0x6c, 0x0d, 0xfb, 0x21, 0x74, 0x44, 0x9e, 0x47, 0x4d, 0x32, 0x4e,
	0x5a, 0x4a, 0x48, 0x39, 0xf6, 0x04, 0xcb, 0xb0, 0x97, 0x66, 0xb6, 0xe1, 0x95, 0x76, 0xb2, 0x26,
	0x45, 0x3f, 0x84, 0xa1, 0xba, 0xb4, 0xce, 0xf4, 0x25, 0x67, 0x41, 0xa1, 0x1f, 0x33, 0xde, 0x90,
	0x4d, 0xb5, 0xb2, 0xc4, 0x56, 0x71, 0x1b, 0x36, 0x66, 0xe1, 0x77, 0x19, 0x99, 0x16, 0x43, 0x7c,
	0x0e, 0xa5, 0x3b, 0x9c, 0xe3, 0x10, 0x4f, 0x43, 0xd5, 0xb7, 0xe5, 0xcb, 0xf5, 0x63, 0x6b, 0xa1,
	0xa4, 0xdb, 0xdc, 0x83, 0xeb, 0xeb, 0x61, 0x04, 0x29, 0xd1, 0x6f, 0xa5, 0x37, 0x34, 0xd0, 0xf9,
	0x19, 0x6e, 0xc2, 0x7a, 0xdd, 0xe8, 0x2c, 0xcd, 0x65, 0xf1, 0x52, 0x35, 0xa5, 0xeb, 0x57, 0xb7,
	0x81, 0xab, 0xb0, 0xdc, 0x37, 0x46, 0xa4, 0x9c, 0x74, 0x2d, 0x56, 0x0c, 0xb4, 0xd0, 0x49, 0x92,
	0x29, 0xe9, 0x5a, 0x3e, 0x22, 0x2b, 0x8c, 0x4c, 0x73, 0x7a, 0x13, 0x8b, 0xb0, 0x36, 0x76, 0x4d,
	0xc4, 0xd9, 0x0a, 0xaf, 0x1e, 0x7b, 0x46, 0xdd, 0xd6, 0xfe, 0xad, 0x96, 0x8a, 0x6d, 0xe3, 0x13,
	0x28, 0xa4, 0x52, 0x8d, 0xc6, 0x7e, 0x27, 0xec, 0x0e, 0x45, 0x72, 0xbc, 0x3b, 0xbb, 0xe1, 0x25,
	0xd6, 0x71, 0x97, 0xd9, 0xe1, 0xea, 0xec, 0x85, 0x5a, 0x22, 0x8a, 0x69, 0x62, 0x5f, 0xf6, 0xc3,
	0x50, 0xdd, 0x36, 0x33, 0x83, 0xd4, 0xac, 0x84, 0x5b, 0xf0, 0x8c, 0x2b, 0xad, 0x5a, 0x89, 0xce,
	0xac, 0x4f, 0xc8, 0x19, 0x29, 0x7c, 0x95, 0x3b, 0xd1, 0x60, 0x07, 0xa3, 0xad, 0xca, 0x4b, 0x36,
	0x94, 0xe8, 0x26, 0x45, 0xac, 0x1c, 0xba, 0x36, 0x36, 0x0f, 0x52, 0xd9, 0x20, 0x60, 0xc4, 0x0e,
	0x11, 0x60, 0xa1, 0xca, 0xc5, 0x59, 0x96, 0xb2, 0xe7, 0x41, 0x9a, 0x1c, 0xb4, 0xe4, 0x9c, 0x54,
	0x75, 0x2f, 0x32, 0x63, 0x48, 0x89, 0x16, 0x3b, 0xc2, 0x1d, 0x28, 0x4e, 0xb9, 0xea, 0xb2, 0xe6,
	0x0d, 0x09, 0x52, 0xce, 0xb2, 0x17, 0xa3, 0x57, 0x4f, 0x7a, 0x6b, 0xbc, 0xa9, 0x33, 0x23, 0x1d,
	0x59, 0x76, 0x8c, 0xaf, 0xe1, 0x64, 0x0a, 0x18, 0xbd, 0xa2, 0x66, 0x74, 0x32, 0xdc, 0x09, 0xeb,
	0xb5, 0x8a, 0x5b, 0xec, 0x64, 0x26, 0x5c, 0x6a, 0xa8, 0x46, 0xc6, 0x50, 0xe4, 0x15, 0x4f, 0x88,
	0x9d, 0x62, 0x09, 0x76, 0x6e, 0x02, 0x4d, 0x49, 0xe7, 0x3e, 0x35, 0xb2, 0xc9, 0x45, 0x8b, 0xbd,
	0xc4, 0x53, 0x38, 0xba, 0x41, 0xe8, 0x9a, 0x8c, 0xc9, 0xa7, 0x52, 0xb8, 0xcc, 0x90, 0xf5, 0xb6,
	0xa1, 0xcf, 0xbd, 0xd3, 0xec, 0xd5, 0xcc, 0xdb, 0x66, 0xd0, 0xa6, 0xb4, 0xb2, 0x2a, 0xe3, 0xa0,
	0xff, 0xeb, 0x30, 0xe5, 0x53, 0x74, 0xfe, 0xc3, 0x30, 0xd5, 0x59, 0xcb, 0x7e, 0x99, 0x49, 0x6f,
	0x9d, 0x14, 0x67, 0x64, 0xac, 0x4f, 0xb9, 0x38, 0xb3, 0xc3, 0xee, 0x52, 0xc4, 0x2a, 0x78, 0x0c,
	0x87, 0x3f, 0x42, 0x53, 0x52, 0x91, 0x54, 0x75, 0xf6, 0xe6, 0xee, 0x98, 0xfd, 0x3e, 0x8c, 0xce,
	0xec, 0x57, 0x3c, 0x82, 0x83, 0x29, 0xd4, 0x51, 0x4c, 0x61, 0x56, 0x5a, 0xde, 0x92, 0x69, 0x92,
	0xf1, 0x99, 0x89, 0xd9, 0x6f, 0xd5, 0xe5, 0xbf, 0x0b, 0x95, 0x37, 0x7f, 0x0e, 0xff, 0x2c, 0xde,
	0x2f, 0xe4, 0xdf, 0xfe, 0xf8, 0x1e, 0x00, 0x00, 0xff, 0xff, 0xaf, 0xde, 0x8a, 0x43, 0xd3, 0x06,
	0x00, 0x00,
}
